[package]
name = "vss-auth-impls"
description = "Authentication implementations for VSS."
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
jwt = [ "base64", "serde", "serde_json", "openssl" ]
sigs = [ "bitcoin_hashes", "hex-conservative", "secp256k1" ]

[dependencies]
api = { workspace = true }
async-trait = "0.1.13"
base64 = { version = "0.22", optional = true, default-features = false, features = ["std"] }
bitcoin_hashes = { version = "1.0", optional = true, default-features = false }
hex-conservative = { version = "1.0", optional = true, default-features = false }
openssl = { version = "0.10.39", optional = true, default-features = false }
secp256k1 = { version = "0.31", optional = true, default-features = false, features = [ "global-context" ] }
serde = { version = "1.0.184", optional = true, default-features = false, features = ["derive"] }
serde_json = { version = "1.0.45", optional = true, default-features = false, features = ["std"] }

[dev-dependencies]
jsonwebtoken = { version = "9", default-features = false, features = ["use_pem"] }
tokio = { version = "1.30", default-features = false, features = ["rt-multi-thread", "macros"] }
