[package]
name = "vss-impls"
description = "Backend KV store implementations for VSS."
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["postgres-native-tls"]
postgres-native-tls = ["dep:native-tls", "dep:postgres-native-tls"]

[dependencies]
async-trait = "0.1.13"
api = { workspace = true }
chrono = "0.4.16"
tokio-postgres = { version = "0.7.15", features = ["with-chrono-0_4"] }
bytes = "1"
tokio = { version = "1.30", default-features = false, features = ["rt", "macros"] }
native-tls = { version = "0.2.4", optional = true, default-features = false }
postgres-native-tls = { version = "0.5", optional = true, default-features = false, features = ["runtime"] }
log = { version = "0.4.8", default-features = false }

[dev-dependencies]
tokio = { version = "1.30", default-features = false, features = ["rt-multi-thread", "macros"] }
api = { workspace = true, features = ["_test_utils"] }
