[workspace]
resolver = "3"
members = ["server", "api", "impls", "auth-impls"]
default-members = ["server"]

[workspace.package]
version = "0.1.0-alpha.0"
rust-version = "1.85.0"
edition = "2024"
authors = ["Leo Nash <hello@leonash.net>", "Elias Rohrer <dev@tnull.de>"]
license = "MIT OR Apache-2.0"
homepage = "https://lightningdevkit.org/"
repository = "https://github.com/lightningdevkit/vss-server/"

[workspace.dependencies]
api = { package = "vss-api", version = "0.1.0-alpha.0", path = "./api" }
auth-impls = { package = "vss-auth-impls", version = "0.1.0-alpha.0", path = "./auth-impls" }
impls = { package = "vss-impls", version = "0.1.0-alpha.0", path = "./impls" }

[profile.release]
panic = "abort"
opt-level = 3
lto = true

[profile.dev]
panic = "abort"

[workspace.lints.rust.unexpected_cfgs]
level = "forbid"
check-cfg = [
	'cfg(noop_authorizer)',
	'cfg(genproto)',
	'cfg(vss_client_v050_compatibility)',
	'cfg(vss_client_main_compatibility)',
]
