[package]
name = "vss-server"
description = "VSS HTTP server implementation."
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = [ "jwt", "sigs", "postgres-native-tls" ]
jwt = ["auth-impls/jwt"]
sigs = ["auth-impls/sigs"]
postgres-native-tls = ["impls/postgres-native-tls"]

[dependencies]
api = { workspace = true }
auth-impls = { workspace = true }
impls = { workspace = true }

hyper = { version = "1", default-features = false, features = ["server", "http1"] }
http-body-util = { version = "0.1", default-features = false }
hyper-util = { version = "0.1", default-features = false, features = ["tokio"] }
tokio = { version = "1.30", default-features = false, features = ["time", "signal", "rt-multi-thread", "macros"] }
prost = { version = "0.11", default-features = false, features = ["std"] }
bytes = "1"
serde = { version = "1.0.184", default-features = false, features = ["derive"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }
log = { version = "0.4.8", default-features = false, features = ["std"] }
chrono = { version = "0.4.16", default-features = false, features = ["clock"] }
rand = { version = "0.9", default-features = false }

[target.'cfg(noop_authorizer)'.dependencies]
api = { workspace = true, features = ["_test_utils"] }

[target.'cfg(vss_client_v050_compatibility)'.dev-dependencies]
vss-client-v050 = { package = "vss-client-ng", version = "=0.5.0" }

[target.'cfg(vss_client_main_compatibility)'.dev-dependencies]
vss-client-main = { package = "vss-client-ng", git = "https://github.com/lightningdevkit/vss-client.git", branch = "main" }

[lints]
workspace = true
